model:
  _convert_: all
  img_size:
  - 32
  - 128
  max_label_length: 25
  charset_train: AÁÀẠẢÃĂẮẰẲẶẴÂẤẦẨẪẬBCDĐEÈÉẼẺẸÊẾỀỂỄỆFGHIÍÌỈĨỊJKLMNOÒÓỎÕỌÔỐỒỔỖỘƠỚỜỠỞỢPQRSTUÙÚỦŨỤƯỪỨỬỮỰVXYỴÝỲỶỸWZaáàạảãăằắẳẵặâấầẩẫậbcdđeèéẻẽẹêếềểễệfghiíìỉĩịjklmnoòóỏõọôốồổỗộơớờởỡợpqrstuùúủũụưừứửữựvyỳýỷỹỵxwz0123456789'".,()-%@!/:+?&\[]=*#<>
  charset_test: AÁÀẠẢÃĂẮẰẲẶẴÂẤẦẨẪẬBCDĐEÈÉẼẺẸÊẾỀỂỄỆFGHIÍÌỈĨỊJKLMNOÒÓỎÕỌÔỐỒỔỖỘƠỚỜỠỞỢPQRSTUÙÚỦŨỤƯỪỨỬỮỰVXYỴÝỲỶỸWZaáàạảãăằắẳẵặâấầẩẫậbcdđeèéẻẽẹêếềểễệfghiíìỉĩịjklmnoòóỏõọôốồổỗộơớờởỡợpqrstuùúủũụưừứửữựvyỳýỷỹỵxwz0123456789'".,()-%@!/:+?&\[]=*#<>
  batch_size: 80
  weight_decay: 0.0
  warmup_pct: 0.075
  name: parseq
  _target_: strhub.models.parseq.system.PARSeq
  patch_size:
  - 4
  - 8
  embed_dim: 384
  enc_num_heads: 6
  enc_mlp_ratio: 4
  enc_depth: 12
  dec_num_heads: 12
  dec_mlp_ratio: 4
  dec_depth: 1
  lr: 0.0007
  perm_num: 6
  perm_forward: true
  perm_mirrored: true
  dropout: 0.1
  decode_ar: true
  refine_iters: 1
data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: data
  train_dir: sin_hw
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: false
  augment: true
  num_workers: 2
trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  val_check_interval: 200
  max_epochs: 100
  gradient_clip_val: 20
  gpus: 2
ckpt_path: null
pretrained: parseq
